// react-resource/samples/trade/src/pages/error/404.tsx
import * as React  from 'react';
import { NavLink } from "react-router-dom"; 
const tip404 =require('assets/imgs/logo.png');
//import logo from '/assets/imgs/404.jpg'
export default class Page404 extends React.Component {
  render() {
    return  <div className="content" style={{
      textAlign: 'center',background:"#fff",height:"750px"
    }}>
      <img src={tip404} alt="404"/>
      <p>访问出错，<NavLink to="/index" style={{color:"blue"}}>返回</NavLink> </p>
    </div>
  }
}

// vue-resource/scaffolds/ko-vue-sample/src/pages/error/404.vue
<template>
   <div>
     <img :src="page404" alt="404"/>
     <div>查看页面不存在，<span class="back-tip" @click="redirct">返回</span></div>
   </div>
</template>

<script>
import page404 from '@public/assets/imgs/404.jpg'
export default {
 data(){
   return {
     page404
   }
 },
 methods:{
   redirct(){
     this.$router.go(-1);
   }
 }
}
</script>

<style>
.back-tip{
 cursor: pointer;
 color:lightblue;
}
</style>
